// Origem: livo@d74d591 · components/ui/Icone.tsx (catálogo único de ícones)
//
// Um nome por ideia, em português, e um só lugar para trocar o desenho.
// Phosphor na versão SSR: funciona em componente de servidor e de cliente.

import {
  AddressBook,
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUpRight,
  ArrowsClockwise,
  Bell,
  Browsers,
  Cake,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChatCircleText,
  Check,
  CheckCircle,
  CircleNotch,
  ClipboardText,
  Clock,
  ClockCountdown,
  Coins,
  Copy,
  CreditCard,
  Crown,
  DeviceMobile,
  DotsThree,
  DotsThreeVertical,
  Eye,
  EyeSlash,
  FileCsv,
  FlowerLotus,
  Funnel,
  Gear,
  Gift,
  Heart,
  Hourglass,
  House,
  Image,
  Info,
  InstagramLogo,
  Lightning,
  ListBullets,
  ListChecks,
  Lock,
  MagnifyingGlass,
  MapPin,
  Megaphone,
  Minus,
  Money,
  NotePencil,
  Package,
  Palette,
  PaperPlaneTilt,
  Pause,
  PencilSimple,
  Percent,
  Phone,
  Play,
  Plus,
  Prohibit,
  QrCode,
  Receipt,
  Scissors,
  ShieldCheck,
  SignIn,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Star,
  Storefront,
  Tag,
  Ticket,
  Timer,
  Trash,
  TrendDown,
  TrendUp,
  Upload,
  User,
  UserMinus,
  UserPlus,
  Users,
  UsersThree,
  Wallet,
  Warning,
  WarningCircle,
  WhatsappLogo,
  X,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon, IconWeight } from "@phosphor-icons/react";

const CATALOGO = {
  inicio: House,
  agenda: CalendarBlank,
  agendaOk: CalendarCheck,
  agendaMais: CalendarPlus,
  agendaX: CalendarX,
  calendario: Calendar,
  clientes: UsersThree,
  cliente: User,
  clienteMais: UserPlus,
  clienteMenos: UserMinus,
  equipe: Users,
  servicos: Sparkle,
  tesoura: Scissors,
  flor: FlowerLotus,
  financeiro: Wallet,
  relatorios: ChartBar,
  mensagens: ChatCircleText,
  ficha: ClipboardText,
  config: Gear,
  pagina: Storefront,
  navegador: Browsers,
  celular: DeviceMobile,
  mais: Plus,
  menos: Minus,
  fechar: X,
  ok: Check,
  okCirculo: CheckCircle,
  voltar: ArrowLeft,
  avancar: ArrowRight,
  seta: ArrowUpRight,
  abrir: ArrowSquareOut,
  esquerda: CaretLeft,
  direita: CaretRight,
  baixo: CaretDown,
  menu: DotsThree,
  menuVertical: DotsThreeVertical,
  buscar: MagnifyingGlass,
  filtro: Funnel,
  ajustes: SlidersHorizontal,
  editar: PencilSimple,
  nota: NotePencil,
  apagar: Trash,
  ver: Eye,
  esconder: EyeSlash,
  pausar: Pause,
  retomar: Play,
  relogio: Clock,
  contagem: ClockCountdown,
  ampulheta: Hourglass,
  cronometro: Timer,
  whatsapp: WhatsappLogo,
  instagram: InstagramLogo,
  telefone: Phone,
  local: MapPin,
  sino: Bell,
  enviar: PaperPlaneTilt,
  presente: Gift,
  bolo: Cake,
  estrela: Star,
  coracao: Heart,
  coroa: Crown,
  pacote: Package,
  percentual: Percent,
  cupom: Ticket,
  etiqueta: Tag,
  dinheiro: Money,
  moedas: Coins,
  cartao: CreditCard,
  pix: QrCode,
  recibo: Receipt,
  comissao: Coins,
  retorno: ArrowsClockwise,
  desfazer: ArrowCounterClockwise,
  proibido: Prohibit,
  cadeado: Lock,
  entrar: SignIn,
  sair: SignOut,
  enviarArquivo: Upload,
  planilha: FileCsv,
  contatos: AddressBook,
  copiar: Copy,
  imagem: Image,
  paleta: Palette,
  raio: Lightning,
  megafone: Megaphone,
  escudo: ShieldCheck,
  lista: ListBullets,
  checklist: ListChecks,
  grade: SquaresFour,
  alta: TrendUp,
  baixa: TrendDown,
  aviso: Warning,
  alerta: WarningCircle,
  info: Info,
  carregando: CircleNotch,
} satisfies Record<string, Icon>;

export type NomeIcone = keyof typeof CATALOGO;

export function Icone({
  nome,
  tamanho = 20,
  peso = "regular",
  className,
  rotulo,
}: {
  nome: NomeIcone;
  tamanho?: number;
  peso?: IconWeight;
  className?: string;
  /** só quando o ícone carrega sentido sozinho */
  rotulo?: string;
}) {
  const C = CATALOGO[nome];
  return (
    <C
      size={tamanho}
      weight={peso}
      className={className}
      aria-hidden={rotulo ? undefined : true}
      aria-label={rotulo}
    />
  );
}
